pipeline 
{
  
  agent any
  stages {

    stage('build') {
      steps {
        sh "building the application"
      }
    }

    stage('test') {
      steps {
        sh "testing the application"
      }
    }

    stage('deploy') {
      steps {
        sh "deploying the application"
      }
    }
  }
}